### ISSUE TITLE
Add support for `Age` header

### ISSUE THREAD

**Issue by vincentmrg** [hyperium/headers#101]
Hello,
It would be nice to implement the `Age` header (used by proxy caches).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age

**Comment by seanmonstar** [comment]
This seems like a fine addition. Something like:

- `pub struct Age(u32)` (or should it be `u64`?)
- A constructor or two: `from_seconds()`? Or perhaps `From<Duration>` that converts it into seconds?
- An accessor `fn seconds() -> u32 (u64?)` to get the seconds.

**Comment by vincentmrg** [comment]
As stated in this documentation (https://httpwg.org/specs/rfc7234.html#header.age) a u32 should be fine.

The value of this header needs to be obtained by computation (https://httpwg.org/specs/rfc7234.html#rfc.section.4.2.3), so I guess an implementation of `From<Duration>` might be convenient.

If I can help with the implementation, do not hesitate to let me know.

**Comment by seanmonstar** [comment]
Sure, if you want to make a PR, that'd be great!

**Comment by vincentmrg** [comment]
Finally I reused an existing `Seconds` struct, let me know if it's ok.
