### ISSUE TITLE
Creating a &'static HeaderName

### ISSUE THREAD

**Issue by zesterer** [hyperium/headers#143]
Hi,

The `Header` trait requires a `name` function that returns a `&'static HeaderName`. However, none of the methods used to construct a `HeaderName` are marked `const` (and so cannot be used to create a regular static, either explicitly or via promotion of a local temporary), so there appears to only be two possible ways to write a valid implementation of `Header::name`:

1) Box and then leak a `HeaderName` on every call

2) Set up a `lazy_static` (or equivalent via new primitives like `LazyCell`) that uses internal mutability to lazily initiate a `HeaderName`

Both of these approaches are undesirable for fairly clear reasons, the first especially, which leads me to the question:

What *is* the intended approach when implementing this trait?

<spoiler>
Or, alternatively, would it be possible to do one of the following?

1) Make some of the methods used to create `HeaderName` `const` (as is the case for `HeaderValue`)

2) Have `Header::name` return `Cow<'static, HeaderName>`
</spoiler>

**Comment by seanmonstar** [comment]
The expected options are:

- Use an existing constant.
- Create a lazy static one.
- Eventually use `const fn`s in `http`.

**Comment by zesterer** [comment]
Unfortunately, only the `lazy_static` route is available to me right now. I guess it'll have to do.
