### ISSUE TITLE
Should fields that contain values in "seconds" use `Duration`?

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/headers#2]
Some headers use a single integer to represent time in seconds, like:

- `Retry-After: 300`
- `Access-Control-Max-Age: 6000`
- `Cache-Control: max-age=6000`

Should the value be exposed as a `Duration` instead of just a `u64`? That may make it clearer what the value actually means.

There could be a sealed trait used for the constructors that is implemented for `u64` and `Duration`, so that people can use either (in case someone really wants to say `RetryAfter::new(300)` instead of `RetryAfter::new(Duration::from_secs(300))`).

**Comment by lnicola** [comment]
I think it's all right to be opinionated and use strong types.

**Comment by seanmonstar** [comment]
The resolution is that yes, these types will treat these "seconds" as `Duration`s.
