### ISSUE TITLE
Does FlatCsv correctly handle commas in quoted strings?

### ISSUE THREAD

**Issue by algermissen** [hyperium/headers#23]
Looking thgroughthe code, it seems that multi-valued headers will just be split at each comma, even if the comma appears inside a quoted string.

Can you clarify whether I am missing something?

**Comment by seanmonstar** [comment]
You're correct. Sigh, that'll complicate the iterator. Though, only some headers use quoted values, right? Maybe there could be a second method to create the slower iterator.
