### ISSUE TITLE
Core Header trait

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/headers#24]
This issue is to discuss the core `Header` trait design.

It's currently this:

```rust
pub trait Header {
    /// The name of this header.
    const NAME: &'static HeaderName;

    /// Decode this type from a `HeaderValue`.
    fn decode(values: &mut Values) -> Option<Self>
    where
        Self: Sized;

    /// Encode this type to a `HeaderMap`.
    ///
    /// This function should be infallible. Any errors converting to a
    /// `HeaderValue` should have been caught when parsing or constructing
    /// this value.
    fn encode(&self, values: &mut ToValues);
}

/// An iterator of `HeaderValue`s supplied to `Header::decode`.
#[derive(Debug)]
pub struct Values<'a> {
    // ..
}

/// A builder to append `HeaderValue`s to during `Header::encode`.
#[derive(Debug)]
pub struct ToValues<'a> {
    // ..
}

impl<'a> ToValues<'a> {
    /// Append the `HeaderValue` to the existing list of headers.
    ///
    /// While this can be called multiple times, *most* headers should only
    /// call this once. The exceptions are outliers like `Set-Cookie`.
    pub fn append(&mut self, value: HeaderValue) {
        // ..
     }

    /// Append the `impl Display` to the list of headers.
    ///
    /// # Panics
    ///
    /// Encoding `HeaderValue`s is expected to be infallible. However, not
    /// all UTF-8 sequences are valid for a `HeaderValue`. The type passed
    /// here must ensure that its resulting string is a valid `HeaderValue`.
    pub fn append_fmt<T: fmt::Display>(&mut self, fmt: T) {
        // ..
     }
}
```

Is this a good design?

**Comment by seanmonstar** [comment]
cc @carllerche @Eijebong @sfackler @algermissen

**Comment by carllerche** [comment]
I was hoping to make the `Header` trait a bit more generic and less dependent on custom structs. Something like:

```rust
pub trait Header {
    /// The name of this header.
    const NAME: &'static HeaderName;

    /// Decode this type from a `HeaderValue`.
    fn decode<I: Iterator<Item = HeaderValue>>(src: &mut I) -> Option<Self>
    where
        Self: Sized;

    /// Encode this type to `HeaderValue` values
    fn encode<E: Extend<HeaderValue>>(&self, dst: &mut E);
}
```

This would allow encoding a header to an arbitrary destination.

Also, is there a reason why `decode` doesn't return an error type with the decode error reason?

**Comment by seanmonstar** [comment]
One noteworthy detail currently is that in `decode`, the iterator is currently checked that it's been exhausted after calling `Header::decode`. This is useful for many cases, when a header is not supposed to have more than one value. However, it *does* seem like something that specific header types could enforce instead.

**Comment by seanmonstar** [comment]
> Is there a reason why decode doesn't return an error type with the decode error reason?

I started with returning an error, and it makes `HeaderMapExt::typed_get` return either `Option<Result<H, Error>>` or `Result<Option<H>, Error>`. But I feel it makes *using* typed headers more annoying, and I found that in my own usage, and anecdotally in Servo as well, the error was just ignored anyways.

**Comment by seanmonstar** [comment]
> I am not too fixated on using `Extend` specifically. I mostly care about using a trait that decouples `HeaderMap` and doesn't use a custom struct.

It could be exposed the other way around: something that implements `Header` could have an `Iterator<Item=HeaderValue>`.

```rust
pub trait Header {
    /// The name of this header.
    const NAME: &'static HeaderName;

    /// Decode this type from a `HeaderValue`.
    fn decode<'i, I: Iterator<Item = &'i HeaderValue>>(src: &mut I) -> Option<Self>
    where
        Self: Sized;

    type Encode: Iterator<Item = HeaderValue>;
    /// Encode this type to `HeaderValue` values
    fn encode(&self) -> Self::Encode;
}
```

**Comment by carllerche** [comment]
@seanmonstar re the exhaustion check, that does not seem like something that should be baked into the trait. It can be implemented with an iterator decorator that the implementations apply. This shouldn’t be a problem if the trait is implemented via a macro.

Re the error, swallowing it seems extra bad. Imo it should be Result<Option<T>, E>. There are plenty of cases where an error would be handled differently than an omission. Servers would respond with 400 vs processing the request. 

Also, adding a shim that maps an error to Option is easy but the reverse is not.

**Comment by carllerche** [comment]
Also, encode returning an iterator seems fine.

**Comment by carllerche** [comment]
@seanmonstar Each header could have a new-type wrapping the iterator? It's more annoying, but also could be generated by the macro.

Either way though.
