### ISSUE TITLE
Expose HSTS struct fields

### ISSUE THREAD

**Issue by Darkspirit** [hyperium/headers#61]
Current code allows creation of an HSTS header, but no access to its contents.
include_subdomains and max_age are private. Created https://github.com/servo/servo/pull/25404 as temporary hotfix.
https://github.com/hyperium/headers/blob/0c42ad8cf56f9af28973c3da71616fa478781fdf/src/common/strict_transport_security.rs#L42-L51

**Comment by seanmonstar** [comment]
Should be easy to add getter methods.
