### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by coolreader18** [hyperium/headers#80]
Hi,
With tokio 1.0 and many ecosystem crates depending on `bytes 1.0` it'd be great if a new version of headers could be cut (given that master depends on bytes 1.0 now) so that there are less duplicate dependencies around.

**Comment by coolreader18** [comment]
Also, warp almost supports tokio 1.0, so it'd be good to have that in before a new version is cut.

**Comment by seanmonstar** [comment]
v0.3.3 has been published! :D
